# Generated by Django 2.2 on 2020-11-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
